const DEFAULT_SCHEMA={monday:{name:'Maandag',type:'pull',exercises:[{naam:'Zittend stang naar borst trekken',spier:'Rug',gewicht:60},{naam:'Touw naar beneden trekken',spier:'Tricep',gewicht:27.5},{naam:'T-bar row',spier:'Rug',gewicht:40}]},wednesday:{name:'Woensdag',type:'legs',exercises:[{naam:'Hack squat',spier:'Bovenbenen',gewicht:40},{naam:'Calf raise',spier:'Kuiten',gewicht:45},{naam:'Leg curl',spier:'Hamstrings',gewicht:''}]},friday:{name:'Vrijdag',type:'push',exercises:[{naam:'Chest press',spier:'Borst',gewicht:68},{naam:'Shoulder press',spier:'Schouders',gewicht:20},{naam:'Bicep curl',spier:'Biceps',gewicht:10}]}};

const clone=value=>JSON.parse(JSON.stringify(value));
const storedSchema=localStorage.getItem('workoutSchema');
let schema=storedSchema?JSON.parse(storedSchema):clone(DEFAULT_SCHEMA);
let history=JSON.parse(localStorage.getItem('workoutHistory')||'[]');
let toastTimer;
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const formatNumber=value=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:1}).format(value||0);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const typeLabel={pull:'Pull · Rug & triceps',push:'Push · Borst & schouders',legs:'Legs · Benen',full:'Full body'};

function saveSchema(){localStorage.setItem('workoutSchema',JSON.stringify(schema));}
function saveHistory(){localStorage.setItem('workoutHistory',JSON.stringify(history));}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200);}
function getVolume(workout){return workout.exercises.reduce((sum,ex)=>sum+(Number(ex.weight)||0)*(Number(ex.reps)||0)*(Number(ex.sets)||0),0);}
function dateLabel(value,short=false){return new Intl.DateTimeFormat('nl-NL',short?{day:'numeric',month:'short'}:{weekday:'short',day:'numeric',month:'short'}).format(new Date(value));}
function totalVolume(){return history.reduce((sum,item)=>sum+getVolume(item),0);}
function getRecords(){const map={};history.forEach(workout=>workout.exercises.forEach(ex=>{if(!map[ex.name]||ex.weight>map[ex.name].weight)map[ex.name]={name:ex.name,muscle:ex.muscle,weight:Number(ex.weight)||0,date:workout.date};}));return Object.values(map).filter(x=>x.weight).sort((a,b)=>b.weight-a.weight);}
function getStreak(){if(!history.length)return 0;const days=[...new Set(history.map(x=>new Date(x.date).toISOString().slice(0,10)))].sort().reverse();let streak=1;for(let i=1;i<days.length;i++){const diff=(new Date(days[i-1])-new Date(days[i]))/86400000;if(diff===1)streak++;else break;}return streak;}
function statCards(){return[{label:'Workouts',value:history.length,icon:'✓',trend:'Totaal gelogd'},{label:'Totaal volume',value:`${formatNumber(totalVolume())} kg`,icon:'↗',trend:'Sets × reps × gewicht'},{label:'Persoonlijke records',value:getRecords().length,icon:'★',trend:'Beste gewichten'},{label:'Huidige reeks',value:`${getStreak()} dag${getStreak()===1?'':'en'}`,icon:'⚡',trend:'Blijf in beweging'}];}
function renderStats(target){$(target).innerHTML=statCards().map(item=>`<article class="stat-card"><span class="stat-icon">${item.icon}</span><small>${item.label}</small><strong>${item.value}</strong><span class="trend">${item.trend}</span></article>`).join('');}

function switchView(view){$$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}View`));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const titles={overview:['JOUW TRAINING','Goed bezig <span>🔥</span>'],plans:['JOUW ROUTINE',"Trainingsschema's"],progress:['JOUW RESULTATEN','Voortgang']};$('#pageEyebrow').textContent=titles[view][0];$('#pageTitle').innerHTML=titles[view][1];if(view==='overview')renderOverview();if(view==='plans')renderPlans();if(view==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'});location.hash=view;}

function renderOverview(){renderStats('#summaryStats');const recent=history.slice(0,4);$('#recentActivities').innerHTML=recent.length?recent.map(item=>`<div class="activity-item"><span class="activity-icon">✓</span><div class="activity-info"><strong>${escapeHtml(item.planName)}</strong><small>${dateLabel(item.date)} · ${item.exercises.length} oefeningen</small></div><span class="activity-value">${formatNumber(getVolume(item))} kg</span></div>`).join(''):'<div class="empty-state"><span>🏋️</span>Je eerste workout verschijnt hier.</div>';renderWeekChart();const first=Object.values(schema)[0];$('#todayTitle').textContent=first?`${first.name}: ${typeLabel[first.type].split(' · ')[0]}`:'Maak je eerste trainingsschema';$('#todaySubtitle').textContent=first?`${first.exercises.length} oefeningen staan voor je klaar.`:'Voeg oefeningen toe en start met trainen.';}
function renderWeekChart(){const labels=['Ma','Di','Wo','Do','Vr','Za','Zo'];const start=new Date();const day=start.getDay()||7;start.setHours(0,0,0,0);start.setDate(start.getDate()-day+1);const values=labels.map((_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return history.filter(x=>new Date(x.date).toDateString()===date.toDateString()).reduce((s,x)=>s+getVolume(x),0);});const max=Math.max(...values,1);$('#weekVolumeLabel').textContent=`${formatNumber(values.reduce((a,b)=>a+b,0))} kg`;$('#weekChart').innerHTML=values.map((value,index)=>`<div class="chart-day"><div class="chart-bar-wrap"><div class="chart-bar" data-value="${formatNumber(value)} kg" style="height:${Math.max(value/max*100,value?5:2)}%"></div></div><small>${labels[index]}</small></div>`).join('');}

function renderPlans(){const entries=Object.entries(schema);$('#plansGrid').innerHTML=entries.length?entries.map(([key,day])=>`<article class="plan-card ${day.type}"><div class="plan-head"><div><h3>${escapeHtml(day.name)}</h3><p>${typeLabel[day.type]}</p></div><button class="icon-btn delete-day" data-key="${key}" aria-label="Dag verwijderen">×</button></div><ol class="exercise-list">${day.exercises.length?day.exercises.map((ex,index)=>`<li class="exercise-row"><span class="exercise-number">${String(index+1).padStart(2,'0')}</span><div class="exercise-info"><strong>${escapeHtml(ex.naam||'Naamloze oefening')}</strong><small>${escapeHtml(ex.spier||'Geen spiergroep')}</small></div><div><span class="exercise-weight">${ex.gewicht?`${formatNumber(ex.gewicht)} kg`:'—'}</span><span class="exercise-actions"><button class="edit-exercise" data-key="${key}" data-index="${index}" aria-label="Bewerken">✎</button><button class="delete-exercise" data-key="${key}" data-index="${index}" aria-label="Verwijderen">×</button></span></div></li>`).join(''):'<li class="empty-state">Nog geen oefeningen</li>'}</ol><div class="plan-actions"><button class="start-plan" data-key="${key}">▶ Start workout</button><button class="add-exercise" data-key="${key}" aria-label="Oefening toevoegen">＋</button></div></article>`).join(''):'<div class="empty-state"><span>▦</span>Maak je eerste trainingsdag.</div>';}

function renderProgress(){renderStats('#progressStats');const workouts=[...history].reverse().slice(-8);const max=Math.max(...workouts.map(getVolume),1);$('#volumeChart').innerHTML=workouts.length?workouts.map(item=>`<div class="chart-day"><div class="chart-bar-wrap"><div class="chart-bar" data-value="${formatNumber(getVolume(item))} kg" style="height:${Math.max(getVolume(item)/max*100,3)}%"></div></div><small>${dateLabel(item.date,true)}</small></div>`).join(''):'<div class="empty-state">Log workouts om je grafiek te vullen.</div>';const records=getRecords().slice(0,8);$('#recordsList').innerHTML=records.length?records.map(item=>`<div class="record-item"><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.muscle||'Oefening')} · ${dateLabel(item.date,true)}</small></div><strong>${formatNumber(item.weight)} kg</strong></div>`).join(''):'<div class="empty-state">Nog geen records.</div>';$('#historyList').innerHTML=history.length?history.map((item,index)=>`<div class="history-row"><div><strong>${escapeHtml(item.planName)}</strong><br><small>${dateLabel(item.date)}</small></div><span class="hide-mobile">${item.exercises.length} oefeningen</span><strong>${formatNumber(getVolume(item))} kg</strong><button class="icon-btn delete-workout" data-index="${index}" aria-label="Workout verwijderen">×</button></div>`).join(''):'<div class="empty-state"><span>↗</span>Je workoutgeschiedenis is nog leeg.</div>';}

function openDayDialog(){$('#dayForm').reset();$('#dayDialog').showModal();}
function saveDay(event){event.preventDefault();const name=$('#dayName').value.trim();if(!name)return;const key=`day_${Date.now()}`;schema[key]={name,type:$('#dayType').value,exercises:[]};saveSchema();$('#dayDialog').close();renderPlans();showToast('Trainingsdag toegevoegd');}
function openExerciseDialog(key,index=''){$('#exerciseForm').reset();$('#exerciseDayKey').value=key;$('#exerciseIndex').value=index;const editing=index!=='';$('#exerciseDialogTitle').textContent=editing?'Oefening bewerken':'Oefening toevoegen';if(editing){const ex=schema[key].exercises[Number(index)];$('#exerciseName').value=ex.naam;$('#exerciseMuscle').value=ex.spier||'';$('#exerciseWeight').value=ex.gewicht||'';}$('#exerciseDialog').showModal();}
function saveExercise(event){event.preventDefault();const key=$('#exerciseDayKey').value,index=$('#exerciseIndex').value;const exercise={naam:$('#exerciseName').value.trim(),spier:$('#exerciseMuscle').value.trim(),gewicht:$('#exerciseWeight').value?Number($('#exerciseWeight').value):''};if(!exercise.naam)return;if(index==='')schema[key].exercises.push(exercise);else schema[key].exercises[Number(index)]=exercise;saveSchema();$('#exerciseDialog').close();renderPlans();showToast(index===''?'Oefening toegevoegd':'Oefening bijgewerkt');}

function openWorkout(key){const entries=Object.entries(schema).filter(([,day])=>day.exercises.length);if(!entries.length){switchView('plans');showToast('Voeg eerst een oefening toe');return;}$('#workoutPlanSelect').innerHTML=entries.map(([itemKey,day])=>`<option value="${itemKey}" ${itemKey===key?'selected':''}>${escapeHtml(day.name)}</option>`).join('');renderWorkoutRows();$('#workoutDialog').showModal();}
function renderWorkoutRows(){const key=$('#workoutPlanSelect').value,day=schema[key];$('#workoutTitle').textContent=day.name;$('#workoutExercises').innerHTML=day.exercises.map((ex,index)=>`<div class="workout-row"><div><strong>${escapeHtml(ex.naam)}</strong><small>${escapeHtml(ex.spier||'Oefening')}</small></div><label><small>GEWICHT</small><input class="log-weight" data-index="${index}" type="number" min="0" step="0.25" value="${ex.gewicht||0}" aria-label="Gewicht voor ${escapeHtml(ex.naam)}"></label><label><small>REPS</small><input class="log-reps" data-index="${index}" type="number" min="0" value="10" aria-label="Herhalingen voor ${escapeHtml(ex.naam)}"></label></div>`).join('');updateLiveVolume();}
function updateLiveVolume(){const volume=$$('.log-weight').reduce((sum,input,index)=>sum+(Number(input.value)||0)*(Number($$('.log-reps')[index].value)||0)*3,0);$('#liveVolume').textContent=`${formatNumber(volume)} kg`;}
function finishWorkout(event){event.preventDefault();const key=$('#workoutPlanSelect').value,day=schema[key];const weights=$$('.log-weight'),reps=$$('.log-reps');const exercises=day.exercises.map((ex,index)=>{const logged={name:ex.naam,muscle:ex.spier,weight:Number(weights[index].value)||0,reps:Number(reps[index].value)||0,sets:3};if(logged.reps>0&&logged.weight>Number(ex.gewicht||0))ex.gewicht=logged.weight;return logged;}).filter(ex=>ex.reps>0);if(!exercises.length){showToast('Vul minimaal één set in');return;}history.unshift({id:Date.now(),date:new Date().toISOString(),planKey:key,planName:day.name,exercises});saveHistory();saveSchema();$('#workoutDialog').close();renderOverview();showToast('Workout opgeslagen — lekker bezig!');}

document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.classList.contains('modal-close')){button.closest('dialog').close();return;}if(button.dataset.view)switchView(button.dataset.view);if(button.dataset.go)switchView(button.dataset.go);if(button.id==='addDayBtn')openDayDialog();if(button.id==='quickWorkoutBtn'||button.id==='heroStartBtn')openWorkout();if(button.classList.contains('add-exercise'))openExerciseDialog(button.dataset.key);if(button.classList.contains('edit-exercise'))openExerciseDialog(button.dataset.key,button.dataset.index);if(button.classList.contains('delete-exercise')&&confirm('Deze oefening verwijderen?')){schema[button.dataset.key].exercises.splice(Number(button.dataset.index),1);saveSchema();renderPlans();}if(button.classList.contains('delete-day')&&confirm('Deze trainingsdag met alle oefeningen verwijderen?')){delete schema[button.dataset.key];saveSchema();renderPlans();}if(button.classList.contains('start-plan'))openWorkout(button.dataset.key);if(button.classList.contains('delete-workout')&&confirm('Deze workout uit je geschiedenis verwijderen?')){history.splice(Number(button.dataset.index),1);saveHistory();renderProgress();}if(button.id==='clearHistoryBtn'&&history.length&&confirm('Je volledige workoutgeschiedenis wissen?')){history=[];saveHistory();renderProgress();showToast('Geschiedenis gewist');}});
$('#dayForm').addEventListener('submit',saveDay);$('#exerciseForm').addEventListener('submit',saveExercise);$('#workoutForm').addEventListener('submit',finishWorkout);$('#workoutPlanSelect').addEventListener('change',renderWorkoutRows);$('#workoutExercises').addEventListener('input',updateLiveVolume);

const initialView=['overview','plans','progress'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
switchView(initialView);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
